// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAha8cyurLEBpwtK6iEauN6m--8jJGjjOs',
    appId: '1:355958751810:web:1c4ff5dcde97f3464b23db',
    messagingSenderId: '355958751810',
    projectId: 'codelab-c9627',
    authDomain: 'codelab-c9627.firebaseapp.com',
    storageBucket: 'codelab-c9627.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATx7jWCegviLhhcVNcvLfWldYdmjkp1bE',
    appId: '1:355958751810:android:65c31ebdb68306d94b23db',
    messagingSenderId: '355958751810',
    projectId: 'codelab-c9627',
    storageBucket: 'codelab-c9627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYr7WiOp8yVWJMKDt_tpfRfzeHHK7Ivk',
    appId: '1:355958751810:ios:7f7158927808655e4b23db',
    messagingSenderId: '355958751810',
    projectId: 'codelab-c9627',
    storageBucket: 'codelab-c9627.appspot.com',
    iosClientId: '355958751810-3c7hbg2j2jno3rh4d9hundmp0cjbcpcd.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotomoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYr7WiOp8yVWJMKDt_tpfRfzeHHK7Ivk',
    appId: '1:355958751810:ios:83c58d4adc3636114b23db',
    messagingSenderId: '355958751810',
    projectId: 'codelab-c9627',
    storageBucket: 'codelab-c9627.appspot.com',
    iosClientId: '355958751810-e357r1smvtr3rp4b440ff0kbcids3hdv.apps.googleusercontent.com',
    iosBundleId: 'com.example.gotomoon.RunnerTests',
  );
}
